# Generated by Django 4.2.1 on 2023-06-03 15:09

import ServerSide.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inami', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'The Belgian INAMI code must be 11 digits long.'), django.core.validators.RegexValidator('^[0-9]+$', 'The Belgian INAMI code must contain only digits.')], verbose_name='Inami')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(validators=[ServerSide.models.age_validator], verbose_name='birth_date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False, verbose_name='record_id')),
                ('record_name', models.CharField(max_length=100, verbose_name='record_name')),
                ('record_content', models.TextField(verbose_name='record_content')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='ServerSide.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorWaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inami', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'The Belgian INAMI code must be 11 digits long.'), django.core.validators.RegexValidator('^[0-9]+$', 'The Belgian INAMI code must contain only digits.')], verbose_name='Inami')),
                ('waitingDoctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminWaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(validators=[ServerSide.models.age_validator], verbose_name='birth_date')),
                ('waitingAdmin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(validators=[ServerSide.models.age_validator], verbose_name='birth_date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecordManagmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerSide.doctor')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerSide.medicalrecord')),
            ],
            options={
                'unique_together': {('record', 'doctor')},
            },
        ),
        migrations.CreateModel(
            name='ApprovedRecordManagmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('until', models.DateTimeField(default=datetime.datetime(2023, 6, 3, 16, 9, 18, 463430, tzinfo=datetime.timezone.utc), verbose_name='until')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerSide.doctor')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerSide.medicalrecord')),
            ],
            options={
                'unique_together': {('record', 'doctor')},
            },
        ),
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerSide.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerSide.patient')),
            ],
            options={
                'unique_together': {('patient', 'doctor')},
            },
        ),
        migrations.CreateModel(
            name='AppointmentRemovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerSide.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerSide.patient')),
            ],
            options={
                'unique_together': {('patient', 'doctor')},
            },
        ),
        migrations.CreateModel(
            name='Appointed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerSide.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerSide.patient')),
            ],
            options={
                'unique_together': {('patient', 'doctor')},
            },
        ),
    ]
