# Generated by Django 4.2.1 on 2023-06-03 21:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedrecordmanagmentrequest',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 22, 30, 7, 142892, tzinfo=datetime.timezone.utc), verbose_name='until'),
        ),
        migrations.CreateModel(
            name='UploadRightRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerSide.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerSide.patient')),
            ],
            options={
                'unique_together': {('patient', 'doctor')},
            },
        ),
        migrations.CreateModel(
            name='ApprovedUploadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('until', models.DateTimeField(default=datetime.datetime(2023, 6, 3, 22, 30, 7, 143893, tzinfo=datetime.timezone.utc), verbose_name='until')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerSide.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerSide.patient')),
            ],
            options={
                'unique_together': {('patient', 'doctor')},
            },
        ),
    ]
