# Generated by Django 4.2.1 on 2023-06-03 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0002_alter_approvedrecordmanagmentrequest_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedrecordmanagmentrequest',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 0, 25, 27, 245511, tzinfo=datetime.timezone.utc), verbose_name='until'),
        ),
        migrations.AlterField(
            model_name='approveduploadrequest',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 0, 25, 27, 246511, tzinfo=datetime.timezone.utc), verbose_name='until'),
        ),
    ]
