# Generated by Django 4.2.1 on 2023-06-04 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0003_alter_approvedrecordmanagmentrequest_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedrecordmanagmentrequest',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 19, 34, 43, 107939, tzinfo=datetime.timezone.utc), verbose_name='until'),
        ),
        migrations.AlterField(
            model_name='approveduploadrequest',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 19, 34, 43, 108935, tzinfo=datetime.timezone.utc), verbose_name='until'),
        ),
    ]
