# Generated by Django 4.2.1 on 2023-06-07 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0007_alter_approvedrecordmanagmentrequest_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='public_key',
            field=models.TextField(default=None, verbose_name='public_key'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='signature',
            field=models.TextField(default=None, verbose_name='signature'),
        ),
        migrations.AlterField(
            model_name='approvedrecordmanagmentrequest',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 18, 13, 20, 89530, tzinfo=datetime.timezone.utc), verbose_name='until'),
        ),
        migrations.AlterField(
            model_name='approveduploadrequest',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 18, 13, 20, 89530, tzinfo=datetime.timezone.utc), verbose_name='until'),
        ),
    ]
