# Generated by Django 4.1.7 on 2023-06-16 06:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ServerSide', '0013_alter_approvedrecordmanagmentrequest_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adminwaitinglist',
            name='waitingAdmin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointed',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ServerSide.doctor'),
        ),
        migrations.AlterField(
            model_name='appointed',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ServerSide.patient'),
        ),
        migrations.AlterField(
            model_name='appointmentremovalrequest',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ServerSide.doctor'),
        ),
        migrations.AlterField(
            model_name='appointmentremovalrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ServerSide.patient'),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ServerSide.doctor'),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ServerSide.patient'),
        ),
        migrations.AlterField(
            model_name='approvedrecordmanagmentrequest',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ServerSide.doctor'),
        ),
        migrations.AlterField(
            model_name='approvedrecordmanagmentrequest',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ServerSide.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='approvedrecordmanagmentrequest',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 7, 22, 31, 322798, tzinfo=datetime.timezone.utc), verbose_name='until'),
        ),
        migrations.AlterField(
            model_name='approveduploadrequest',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ServerSide.doctor'),
        ),
        migrations.AlterField(
            model_name='approveduploadrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ServerSide.patient'),
        ),
        migrations.AlterField(
            model_name='approveduploadrequest',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 7, 22, 31, 323793, tzinfo=datetime.timezone.utc), verbose_name='until'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorwaitinglist',
            name='waitingDoctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner', to='ServerSide.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recordmanagmentrequest',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ServerSide.doctor'),
        ),
        migrations.AlterField(
            model_name='recordmanagmentrequest',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ServerSide.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='uploadrightrequest',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ServerSide.doctor'),
        ),
        migrations.AlterField(
            model_name='uploadrightrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ServerSide.patient'),
        ),
    ]
